export default {
    get: (state) => (name) => state[name],
    dockedMenu: (state) => state.dockedMenu,
    characterName: (state) => state.characterName,
    characterStats: (state) => state.characterStats,
    characterBonusStats: (state) => state.characterBonusStats,
    characterAttributes: (state) => state.characterAttributes,
    characterJobId: (state) => state.characterJobId,
    characterJob: (state) => state.characterJob,
    characterStatusPoints: (state) => state.characterStatusPoints,
    characterBaseLevel: (state) => state.characterBaseLevel,
    characterJobLevel: (state) => state.characterJobLevel,
    characterBaseExp: (state) => state.characterBaseExp,
    characterJobExp: (state) => state.characterJobExp,
    characterHeadStyle: (state) => state.characterHeadStyle,
    characterGender: (state) => state.characterGender,
    characterSkills: (state) => state.characterSkills,
    characterSkillPoints: (state) => state.characterSkillPoints,
    characterLocationId: (state) => state.characterLocationId,
    characterLocation: (state) => state.characterLocation,
    characterSaveLocationId: (state) => state.characterSaveLocationId,
    characterSaveLocation: (state) => state.characterSaveLocation,
    characterZeny: (state) => state.characterZeny,
    travelingToLocation: (state) => state.travelingToLocation,
    characterHp: (state) => state.characterHp,
    characterMp: (state) => state.characterMp,
    fightStatus: (state) => state.fightStatus,
    chatContent: (state) => state.chatContent,
    restInProgress: (state) => state.restInProgress,
    inventory: (state) => state.inventory,
    inventoryWeight: (state) => state.inventoryWeight,
    characterEquipment: (state) => state.characterEquipment,
    showChat: (state) => state.showChat,
    socketConnection: (state) => state.socketConnection,
    allMaps: (state) => state.allMaps
};