export default {
    characterName: '',
    characterHeadStyle: 0,
    characterGender: 'm',
    characterStats: {
        str: 0,
        dex: 0,
        int: 0,
        vit: 0,
        wis: 0,
        luk: 0
    },
    characterJobId: 0,
    characterBaseLevel: 1,
    characterJobLevel: 1,
    characterBaseExp: 0,
    characterJobExp: 0,
    characterStatusPoints: 0,
    characterSkills: {},
    characterSkillPoints: 0,
    characterLocation: 1,
    characterSaveLocation: 1,
    characterHp: 42,
    characterMp: 13,
    characterZeny: 0,
    characterEquipmentTrigger: null,
    characterEquipmentSlots: {
        head: 0,
        body: 0,
        rhand: 0,
        lhand: 0,
        robe: 0,
        shoes: 0,
        acc1: 0,
        acc2: 0
    },
    travelingToLocation: 0,
    restInProgress: false,
    party: [],
    dockedMenu: false,
    fightStatus: false,
    chatContent: [],
    inventory: []
};