<template>
    <section class="text-page">
        <div class="text-page__wrapper">
            <h1>{{ $t('footer.termsAndConditions') }}</h1>

            <p>Rules of RO Idle are simple</p>

            <ul>
                <li>Be respectful to others. Even while being a troll, you can be respectful. There is a person on the other side of the screen. Treat them the way you want to be treated by others</li>
                <li>Bugs will happen, on the outside it looks like a very simple game, while the code on the inside is not. Report bugs and I will try to restore your lost items and as result your time spent on achieving the stuff you were trying to achieve</li>
                <li>Sharing content that is forbidden by law is forbidden in the game. That means no pornography, racism, sexism, religious hate or any kind of harrasment outside of private, party or guild chats.</li>
                <li>In case your character have profanity or inappropriate words in the name. Name can be changed by admin without any notice</li>
                <li>I will not take responsibility over party or guild chats, respective leaders of party and guild should define those rules. Public room chats chats can be brought to admin attention to a point where person can receive mute or ban on the character or account. Private chats, in case person on one side asked the other side to stop, but behaviour continues can be brought to admin attention</li>
                <li>Cheats are "allowed" to be found. If found please report it to admin you will be rewarded in a way that you will keep items generated by cheats if they won't break the game economy or make your character somewhat of a god. Or another reward will be generated for you. In case cheat was used in the dark and was found by admin instead you might be banned. Cheats are considered situations where you receive benefit over other players by using mechanic of the game which was not intented. Visual and small bugs that don't give advantage are not considered cheats.</li>
                <li>Multi-characters are allowed but discouraged. This game is party-oriented</li>
                <li>All content, services, and software on this web site are provided "as is" without warranty of any kind, either express or implied. You assume total responsibility and risk for your use of the web site.</li>
                <li>This website is tracking your action outside of the website. There are no analytics involved.</li>
                <li>Only data which might be storred in your browser by the game are your settings and account data to not require you to login each time you enter. For that this website utilizing browser feature colled Local Storage which is similar, but not Cookies.</li>
                <li>Those rules might and will change with time.</li>
                <li>By playing the game you accept those terms</li>
            </ul>

            <p>Latest update for T&C: 4th April 2021</p>
        </div>
    </section>
</template>

<script>
const termsAndConditionsPage = {};

// Routing
mo.routes.push({
    path: '/terms-and-conditions',
    component: termsAndConditionsPage
});

export default termsAndConditionsPage;
</script>